import type { Problems } from "./types";
export const problems: Problems[] = [
  {
    id: 1,
    name: "Multiples of 3 or 5",
    description: [
      "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6, and 9. The sum of these multiples is 23.",
      "Find the sum of all the multiples of 3 or 5 below the given test case.",
    ],
  },
  {
    id: 2,
    name: "Even Fibonacci Numbers",
    description: [
      "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: ",
      "1, 2, 3, 5, 8, 13, 21, 34, 55, 89 ... ",
      "By considering the terms in the Fibonacci sequence whose values do not exceed given limit, find the sum of the even-valued terms.",
    ],
  },
  {
    id: 3,
    name: "Largest Prime Factor",
    description: [
      "The prime factors of 13195 are 5, 7, 13, and 29.",
      "Find the largest prime factor of the given number",
    ],
  },
  {
    id: 4,
    name: "Largest Palindrome Product",
    description: [
      "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.",
      "Find the largest palindrome made from the product of two numbers with a given number of digits.",
    ],
  },
  {
    id: 5,
    name: "Smallest Multiple",
    description: [
      "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.",
      "Find the smallest positive number that is evenly divisible (without any remainder) by all of the numbers from 1 to a given number?",
    ],
  },
  {
     id: 6,
     name: "Sum Square Difference",
     description: [
       "The sum of the squares of the first ten natural numbers is,",
       "1² + 2² + ... + 10² = 385.", 
       "The square of the sum of the first ten natural numbers is,",
       "(1 + 2 + ... + 10)² = 3025.",
       "Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.",
       "Calculate the difference between the sum of the squares and the square of the sum for the first n natural numbers.",
     ],
  },
  {
     id: 7,
     name: "10 001st Prime",
     description: [
       "By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.",
       "Now find the nth prime number.",
     ],
  },
  {
      id: 8,
      name: "Largest Product in a Series",
      description: [
        "The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.",
        "For example, in the series 21345674, the 3 adjacent digits with the greatest product are 5 × 6 × 7 = 210.",
        "Find the n adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?",
      ],
  },
  {
      id: 9,
      name: "Special Pythagorean Triplet",
      description: [
        "A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,",
        "a² + b² = c².",
        "There exists exactly one Pythagorean triplet for which a + b + c = 1000.",
        "Find the product a × b × c for the Pythagorean triplet where a + b + c equals the given sum.",
      ],
  },
  {
    id: 10,
    name: "Summation of Primes",
    description: [
      "The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.",
      "Find the sum of all the primes below the given number.",
    ],
  },
  {
      id: 11,
      name: "Largest Product in a Grid",
      description: [
        "In a 20×20 grid of numbers, four numbers can be selected along any direction: up, down, left, right, or diagonally",
        "Find the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid.",
        "example: the greatest product of 3 adjacent numbers in a 5 x 5 grid",
        "08 02 22 97 38",
        "04 42 16 73 38",
        "80 69 36 41 72",
        "20 73 35 29 78",
        "01 70 54 71 83",
        "answers: 72 × 78 × 83 = 466,128",
      ],
  },
  {
      id: 12,
      name: "Highly Divisible Triangular Number",
      description: [
        "The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28, The first ten terms would be",
        "1, 3 ,6 ,10, 15, 21, 28, 36, 45, 55",
        "Let us list the factors of the first seven triangle numbers:",
        "1: 1",
        "3: 1, 3",
        "6: 1, 2, 3, 6",
        "10: 1, 2, 5, 10",
        "15: 1, 3, 5, 15",
        "21: 1, 3, 7, 21",
        "28: 1, 2, 4, 7, 14, 28",
        "We can see that 28 is the first triangle number to have over five divisors.",
        "What is the value of the first triangle number to have over n divisors?",
      ],
  },
  {
      id: 13,
      name: "Longest Collatz Sequence",
      description: [
        "The following iterative sequence is defined for the set of positive integers:",
        "n -> n/2 (if n is even),",
        "n -> 3n + 1 (if n is odd).",
        "Using the rule above and starting with 13, we generate the sequence:",
        "13 -> 40 -> 20 -> 10 -> 5 -> 16 -> 8 -> 4 -> 2 -> 1.",
        "It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.",
        "Which starting number, under the given limit, produces the longest chain?",
        "NOTE: Once the chain starts the terms are allowed to go above million.",
      ],
  },
  {
      id: 14,
      name: "Lattice Paths",
      description: [
        "Starting in the top left corner of a 2×2 grid, and only being able to move right and down, there are exactly 6 routes to the bottom right corner.",
        {
          src: "/images/problem-14.png",
          alt: "2×2 lattice Paths",
        },
        "How many such routes are there through a given n x n grid?",
      ],
  },
  {
      id: 16,
      name: "Power Digit Sum",
      description: [
        "2¹⁵ = 32768 and the sum of its digits is,",
        "3 + 2 + 7 + 6 + 8 = 26.",
        "What is the sum of the digits of the number 2ⁿ?",
      ],
    },
];
